### ISSUE TITLE
Use try-catch properly

### ISSUE THREAD

**Issue by edisonzsq** [franpoh/bookloop#34]
Consider the following code.

```js
try {
      const result = await bookAPI.post('/protected/addwish', {
        indexId: data.indexId
      });
      console.log('addwish result: ', result.data);
      console.log('addwish result wishlist: ', result.data.data.wishlist);

      return result.data.data.wishlist;

    } catch(error) {
      console.log('addwishlist error: ', error)

      return data.userWishlist;
    };
```
When you catch an error, what you want to do is to throw it. When you throw an error, the upper stack of the code has to "handle" the error and produce an alternate flow. We don't usually return something in the `catch` block.

**Comment by CGW-G1** [comment]
return in catch block removed, replaced with: 
let result = {
    data: {
      data: null
    }
  };

  try {
    result = await bookAPI.post('/protected/addwish', {
      indexId: data.indexId
    });
    console.log('addwish result: ', result.data);
    console.log('addwish result wishlist: ', result.data.data.wishlist);

    // return result.data.data.wishlist;

  } catch (error) {
    console.log('addwishlist error: ', error);
  } finally {
    return result.data;
  };
};
